# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: definitions.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64\x65\x66initions.proto\x12\x1aminimumreproducibleexample\" \n\rPublicRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x0ePublicResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\rHiddenRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x0eHiddenResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2y\n\rPublicService\x12h\n\x0f\x44oPublicRequest\x12).minimumreproducibleexample.PublicRequest\x1a*.minimumreproducibleexample.PublicResponse2y\n\rHiddenService\x12h\n\x0f\x44oHiddenRequest\x12).minimumreproducibleexample.HiddenRequest\x1a*.minimumreproducibleexample.HiddenResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'definitions_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PUBLICREQUEST._serialized_start=49
  _PUBLICREQUEST._serialized_end=81
  _PUBLICRESPONSE._serialized_start=83
  _PUBLICRESPONSE._serialized_end=116
  _HIDDENREQUEST._serialized_start=118
  _HIDDENREQUEST._serialized_end=150
  _HIDDENRESPONSE._serialized_start=152
  _HIDDENRESPONSE._serialized_end=185
  _PUBLICSERVICE._serialized_start=187
  _PUBLICSERVICE._serialized_end=308
  _HIDDENSERVICE._serialized_start=310
  _HIDDENSERVICE._serialized_end=431
# @@protoc_insertion_point(module_scope)
