# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import definitions_pb2 as definitions__pb2


class PublicServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DoPublicRequest = channel.unary_unary(
                '/minimumreproducibleexample.PublicService/DoPublicRequest',
                request_serializer=definitions__pb2.PublicRequest.SerializeToString,
                response_deserializer=definitions__pb2.PublicResponse.FromString,
                )


class PublicServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DoPublicRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PublicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DoPublicRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.DoPublicRequest,
                    request_deserializer=definitions__pb2.PublicRequest.FromString,
                    response_serializer=definitions__pb2.PublicResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'minimumreproducibleexample.PublicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PublicService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DoPublicRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/minimumreproducibleexample.PublicService/DoPublicRequest',
            definitions__pb2.PublicRequest.SerializeToString,
            definitions__pb2.PublicResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class HiddenServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DoHiddenRequest = channel.unary_unary(
                '/minimumreproducibleexample.HiddenService/DoHiddenRequest',
                request_serializer=definitions__pb2.HiddenRequest.SerializeToString,
                response_deserializer=definitions__pb2.HiddenResponse.FromString,
                )


class HiddenServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DoHiddenRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HiddenServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DoHiddenRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.DoHiddenRequest,
                    request_deserializer=definitions__pb2.HiddenRequest.FromString,
                    response_serializer=definitions__pb2.HiddenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'minimumreproducibleexample.HiddenService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HiddenService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DoHiddenRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/minimumreproducibleexample.HiddenService/DoHiddenRequest',
            definitions__pb2.HiddenRequest.SerializeToString,
            definitions__pb2.HiddenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
